
//----------------------------------------------------
// The following code was generated by CUP v0.10g
// Mon Apr 07 14:03:34 CDT 2025
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int TIMES = 12;
  static final int RBRACK = 9;
  static final int AND = 20;
  static final int LT = 16;
  static final int ELSE = 28;
  static final int SEMICOLON = 3;
  static final int STRUCT = 25;
  static final int PLUS = 10;
  static final int INT = 33;
  static final int OR = 21;
  static final int RBRACE = 7;
  static final int RPAREN = 5;
  static final int WHILE = 29;
  static final int LBRACK = 8;
  static final int RETURN = 26;
  static final int IF = 27;
  static final int GT = 18;
  static final int LPAREN = 4;
  static final int LBRACE = 6;
  static final int ID = 31;
  static final int VOID_TYPE = 24;
  static final int LE = 17;
  static final int STRING = 32;
  static final int COMMA = 2;
  static final int EOF = 0;
  static final int DIVIDE = 13;
  static final int GE = 19;
  static final int MINUS = 11;
  static final int error = 1;
  static final int INT_TYPE = 23;
  static final int ASSIGN = 22;
  static final int EQ = 14;
  static final int FOR = 30;
  static final int NEQ = 15;
}

